### ISSUE TITLE
audio doesn't work.

### ISSUE THREAD

**Issue by bri2cute** [bri2cute/bri2cute.github.io#1]
background audio won't play on the intended "collage.html" site.

**Comment by bri2cute** [comment]
removed the bg audio, changed it so that it instead plays when clicking IMG1 on the website's collage section.

**Comment by bri2cute** [comment]
removed the bg audio, changed it so that it instead plays when clicking IMG1 on the website's collage section.

**Comment by bri2cute** [comment]
nvm, audio fix doesnt work anymore after put into "media" folder.

**Comment by reallythin** [comment]
made changes to bgaudio,mp3, will test if this works now.
